# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='seen_status',
            field=models.BooleanField(default=False),
        ),
    ]
