# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20160522_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by', models.CharField(max_length=10)),
            ],
        ),
    ]
