# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='search_by',
            field=models.CharField(default='title', max_length=10),
        ),
    ]
